language: generic
dist: xenial
sudo: required
deploy:
  provider: releases
  api_key:
    secure: c6931b0ff3f2b65d04d188395b7fceb63c238e3b
  file: dummy_gen_asset.txt
  on:
    repo: hashitop/test02_releases
  skip_cleanup: true
